cd sportsCenter
mvn spring-boot:run

CREATE TABLE TOOL_MANAGEMENT(
    TOOL_MANAGEMENT_ID NUMBER(10) PRIMARY KEY NOT NULL,
    RESERVE_MANAGEMENT_ID NUMBER(10) NOT NULL REFERENCES RESERVE_MANAGEMENT(RESERVE_MANAGEMENT_ID),
    TOOL_ID NUMBER(10) NOT NULL REFERENCES LENDING_TOOL(TOOL_ID),
    TOOL_NUMBER NUMBER(10) NOT NULL,
);
CREATE SEQUENCE SEQ_RESERVE_MANAGEMENT NOCACHE;
CREATE SEQUENCE SEQ_TOOL_MANAGEMENT NOCACHE;
CREATE SEQUENCE SEQ_TOOL NOCACHE;
CREATE SEQUENCE SEQ_FACILITY NOCACHE;