--------------------------------------------------------
--  �ļ��Ѵ��� - ������-����-01-2023   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table BULLETIN_BOARD
--------------------------------------------------------

  CREATE TABLE "KIKAKU_USER"."BULLETIN_BOARD" 
   (	"BULLETIN_BOARD_ID" NUMBER(10,0), 
	"CREATE_TIME" TIMESTAMP (6), 
	"BBS_CONTENT" VARCHAR2(400 BYTE), 
	"BBS_AUTHOR" VARCHAR2(40 BYTE), 
	"BBS_TITLE" VARCHAR2(40 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "KIKAKU_USER"."BULLETIN_BOARD"."BULLETIN_BOARD_ID" IS '��ʾ��ID';
   COMMENT ON COLUMN "KIKAKU_USER"."BULLETIN_BOARD"."CREATE_TIME" IS '��Ҏ�r�g';
   COMMENT ON COLUMN "KIKAKU_USER"."BULLETIN_BOARD"."BBS_CONTENT" IS '��ʾ������';
   COMMENT ON COLUMN "KIKAKU_USER"."BULLETIN_BOARD"."BBS_AUTHOR" IS '��ʾ������';
   COMMENT ON COLUMN "KIKAKU_USER"."BULLETIN_BOARD"."BBS_TITLE" IS '��ʾ�奿���ȥ�';
--------------------------------------------------------
--  DDL for Table LENDING_FACILITY
--------------------------------------------------------

  CREATE TABLE "KIKAKU_USER"."LENDING_FACILITY" 
   (	"FACILITY_ID" NUMBER(10,0), 
	"FACILITY_NAME" VARCHAR2(100 BYTE), 
	"FACILITY_ENG" VARCHAR2(100 BYTE), 
	"EXPLANATION_LONG" VARCHAR2(400 BYTE), 
	"EXPLANATION_SHORT" VARCHAR2(200 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "KIKAKU_USER"."LENDING_FACILITY"."FACILITY_ID" IS 'ʩ�OID';
   COMMENT ON COLUMN "KIKAKU_USER"."LENDING_FACILITY"."FACILITY_NAME" IS 'ʩ�O����ǰ';
   COMMENT ON COLUMN "KIKAKU_USER"."LENDING_FACILITY"."FACILITY_ENG" IS 'ʩ�O��Ӣ����';
   COMMENT ON COLUMN "KIKAKU_USER"."LENDING_FACILITY"."EXPLANATION_LONG" IS '�L���B������';
   COMMENT ON COLUMN "KIKAKU_USER"."LENDING_FACILITY"."EXPLANATION_SHORT" IS '�̤��B������';
--------------------------------------------------------
--  DDL for Table LENDING_TOOL
--------------------------------------------------------

  CREATE TABLE "KIKAKU_USER"."LENDING_TOOL" 
   (	"TOOL_ID" NUMBER(10,0), 
	"TOOL_NAME" VARCHAR2(100 BYTE), 
	"FACILITY_ID" NUMBER(10,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "KIKAKU_USER"."LENDING_TOOL"."TOOL_ID" IS '����ID';
   COMMENT ON COLUMN "KIKAKU_USER"."LENDING_TOOL"."TOOL_NAME" IS '������ǰ';
   COMMENT ON COLUMN "KIKAKU_USER"."LENDING_TOOL"."FACILITY_ID" IS 'ʩ�OID';
--------------------------------------------------------
--  DDL for Table RESERVE_MANAGEMENT
--------------------------------------------------------

  CREATE TABLE "KIKAKU_USER"."RESERVE_MANAGEMENT" 
   (	"RESERVE_MANAGEMENT_ID" NUMBER(10,0), 
	"USER_ID" NUMBER(10,0), 
	"FACILITY_ID" NUMBER(10,0), 
	"CREATE_TIME" TIMESTAMP (6), 
	"RESERVE_DATE" DATE, 
	"HOUR_LIST" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "KIKAKU_USER"."RESERVE_MANAGEMENT"."RESERVE_MANAGEMENT_ID" IS '��sID';
   COMMENT ON COLUMN "KIKAKU_USER"."RESERVE_MANAGEMENT"."USER_ID" IS '��`���`ID';
   COMMENT ON COLUMN "KIKAKU_USER"."RESERVE_MANAGEMENT"."FACILITY_ID" IS 'ʩ�OID';
   COMMENT ON COLUMN "KIKAKU_USER"."RESERVE_MANAGEMENT"."CREATE_TIME" IS '���h�r�g';
   COMMENT ON COLUMN "KIKAKU_USER"."RESERVE_MANAGEMENT"."RESERVE_DATE" IS '��s�ո�';
   COMMENT ON COLUMN "KIKAKU_USER"."RESERVE_MANAGEMENT"."HOUR_LIST" IS '��s�r�g��';
--------------------------------------------------------
--  DDL for Table SPORTSCENTER_USER
--------------------------------------------------------

  CREATE TABLE "KIKAKU_USER"."SPORTSCENTER_USER" 
   (	"USER_ID" NUMBER(10,0), 
	"NAME" VARCHAR2(50 BYTE), 
	"PASSWORD" VARCHAR2(30 BYTE), 
	"EMAIL" VARCHAR2(256 BYTE), 
	"PHONE_NUMBER" VARCHAR2(11 BYTE), 
	"POST" NUMBER(7,0), 
	"DOMICILE" VARCHAR2(200 BYTE), 
	"AUTHORITY" NUMBER(1,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "KIKAKU_USER"."SPORTSCENTER_USER"."USER_ID" IS '��`���`ID';
   COMMENT ON COLUMN "KIKAKU_USER"."SPORTSCENTER_USER"."NAME" IS '��ǰ';
   COMMENT ON COLUMN "KIKAKU_USER"."SPORTSCENTER_USER"."PASSWORD" IS '�ѥ���`��';
   COMMENT ON COLUMN "KIKAKU_USER"."SPORTSCENTER_USER"."EMAIL" IS '��`�륢�ɥ쥹';
   COMMENT ON COLUMN "KIKAKU_USER"."SPORTSCENTER_USER"."PHONE_NUMBER" IS '�Ԓ����';
   COMMENT ON COLUMN "KIKAKU_USER"."SPORTSCENTER_USER"."POST" IS '�]�㷬��';
   COMMENT ON COLUMN "KIKAKU_USER"."SPORTSCENTER_USER"."DOMICILE" IS 'ס��';
   COMMENT ON COLUMN "KIKAKU_USER"."SPORTSCENTER_USER"."AUTHORITY" IS '����';
--------------------------------------------------------
--  DDL for Table TOOL_MANAGEMENT
--------------------------------------------------------

  CREATE TABLE "KIKAKU_USER"."TOOL_MANAGEMENT" 
   (	"TOOL_MANAGEMENT_ID" NUMBER(10,0), 
	"RESERVE_MANAGEMENT_ID" NUMBER(10,0), 
	"TOOL_ID" NUMBER(10,0), 
	"TOOL_NUMBER" NUMBER(10,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "KIKAKU_USER"."TOOL_MANAGEMENT"."TOOL_MANAGEMENT_ID" IS '������sID';
   COMMENT ON COLUMN "KIKAKU_USER"."TOOL_MANAGEMENT"."RESERVE_MANAGEMENT_ID" IS '��sID';
   COMMENT ON COLUMN "KIKAKU_USER"."TOOL_MANAGEMENT"."TOOL_ID" IS '����ID';
   COMMENT ON COLUMN "KIKAKU_USER"."TOOL_MANAGEMENT"."TOOL_NUMBER" IS '�������';
--------------------------------------------------------
--  DDL for Index SYS_C006056
--------------------------------------------------------

  CREATE UNIQUE INDEX "KIKAKU_USER"."SYS_C006056" ON "KIKAKU_USER"."BULLETIN_BOARD" ("BULLETIN_BOARD_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C005931
--------------------------------------------------------

  CREATE UNIQUE INDEX "KIKAKU_USER"."SYS_C005931" ON "KIKAKU_USER"."LENDING_FACILITY" ("FACILITY_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C005989
--------------------------------------------------------

  CREATE UNIQUE INDEX "KIKAKU_USER"."SYS_C005989" ON "KIKAKU_USER"."LENDING_TOOL" ("TOOL_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C006001
--------------------------------------------------------

  CREATE UNIQUE INDEX "KIKAKU_USER"."SYS_C006001" ON "KIKAKU_USER"."RESERVE_MANAGEMENT" ("RESERVE_MANAGEMENT_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C005917
--------------------------------------------------------

  CREATE UNIQUE INDEX "KIKAKU_USER"."SYS_C005917" ON "KIKAKU_USER"."SPORTSCENTER_USER" ("USER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C006013
--------------------------------------------------------

  CREATE UNIQUE INDEX "KIKAKU_USER"."SYS_C006013" ON "KIKAKU_USER"."TOOL_MANAGEMENT" ("TOOL_MANAGEMENT_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table BULLETIN_BOARD
--------------------------------------------------------

  ALTER TABLE "KIKAKU_USER"."BULLETIN_BOARD" MODIFY ("BULLETIN_BOARD_ID" NOT NULL ENABLE);
  ALTER TABLE "KIKAKU_USER"."BULLETIN_BOARD" MODIFY ("CREATE_TIME" NOT NULL ENABLE);
  ALTER TABLE "KIKAKU_USER"."BULLETIN_BOARD" MODIFY ("BBS_CONTENT" NOT NULL ENABLE);
  ALTER TABLE "KIKAKU_USER"."BULLETIN_BOARD" MODIFY ("BBS_AUTHOR" NOT NULL ENABLE);
  ALTER TABLE "KIKAKU_USER"."BULLETIN_BOARD" ADD PRIMARY KEY ("BULLETIN_BOARD_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "KIKAKU_USER"."BULLETIN_BOARD" MODIFY ("BBS_TITLE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table LENDING_FACILITY
--------------------------------------------------------

  ALTER TABLE "KIKAKU_USER"."LENDING_FACILITY" MODIFY ("FACILITY_NAME" NOT NULL ENABLE);
  ALTER TABLE "KIKAKU_USER"."LENDING_FACILITY" ADD PRIMARY KEY ("FACILITY_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table LENDING_TOOL
--------------------------------------------------------

  ALTER TABLE "KIKAKU_USER"."LENDING_TOOL" MODIFY ("TOOL_NAME" NOT NULL ENABLE);
  ALTER TABLE "KIKAKU_USER"."LENDING_TOOL" ADD PRIMARY KEY ("TOOL_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table RESERVE_MANAGEMENT
--------------------------------------------------------

  ALTER TABLE "KIKAKU_USER"."RESERVE_MANAGEMENT" MODIFY ("USER_ID" NOT NULL ENABLE);
  ALTER TABLE "KIKAKU_USER"."RESERVE_MANAGEMENT" MODIFY ("FACILITY_ID" NOT NULL ENABLE);
  ALTER TABLE "KIKAKU_USER"."RESERVE_MANAGEMENT" ADD PRIMARY KEY ("RESERVE_MANAGEMENT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "KIKAKU_USER"."RESERVE_MANAGEMENT" MODIFY ("CREATE_TIME" NOT NULL ENABLE);
  ALTER TABLE "KIKAKU_USER"."RESERVE_MANAGEMENT" MODIFY ("RESERVE_DATE" NOT NULL ENABLE);
  ALTER TABLE "KIKAKU_USER"."RESERVE_MANAGEMENT" MODIFY ("HOUR_LIST" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table SPORTSCENTER_USER
--------------------------------------------------------

  ALTER TABLE "KIKAKU_USER"."SPORTSCENTER_USER" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "KIKAKU_USER"."SPORTSCENTER_USER" MODIFY ("PASSWORD" NOT NULL ENABLE);
  ALTER TABLE "KIKAKU_USER"."SPORTSCENTER_USER" MODIFY ("EMAIL" NOT NULL ENABLE);
  ALTER TABLE "KIKAKU_USER"."SPORTSCENTER_USER" MODIFY ("PHONE_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "KIKAKU_USER"."SPORTSCENTER_USER" MODIFY ("AUTHORITY" NOT NULL ENABLE);
  ALTER TABLE "KIKAKU_USER"."SPORTSCENTER_USER" ADD PRIMARY KEY ("USER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "KIKAKU_USER"."SPORTSCENTER_USER" MODIFY ("POST" NOT NULL ENABLE);
  ALTER TABLE "KIKAKU_USER"."SPORTSCENTER_USER" MODIFY ("DOMICILE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TOOL_MANAGEMENT
--------------------------------------------------------

  ALTER TABLE "KIKAKU_USER"."TOOL_MANAGEMENT" MODIFY ("TOOL_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "KIKAKU_USER"."TOOL_MANAGEMENT" ADD PRIMARY KEY ("TOOL_MANAGEMENT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "KIKAKU_USER"."TOOL_MANAGEMENT" MODIFY ("RESERVE_MANAGEMENT_ID" NOT NULL ENABLE);
  ALTER TABLE "KIKAKU_USER"."TOOL_MANAGEMENT" MODIFY ("TOOL_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table LENDING_TOOL
--------------------------------------------------------

  ALTER TABLE "KIKAKU_USER"."LENDING_TOOL" ADD FOREIGN KEY ("FACILITY_ID")
	  REFERENCES "KIKAKU_USER"."LENDING_FACILITY" ("FACILITY_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table RESERVE_MANAGEMENT
--------------------------------------------------------

  ALTER TABLE "KIKAKU_USER"."RESERVE_MANAGEMENT" ADD FOREIGN KEY ("FACILITY_ID")
	  REFERENCES "KIKAKU_USER"."LENDING_FACILITY" ("FACILITY_ID") ENABLE;
  ALTER TABLE "KIKAKU_USER"."RESERVE_MANAGEMENT" ADD CONSTRAINT "SYS_C006002" FOREIGN KEY ("USER_ID")
	  REFERENCES "KIKAKU_USER"."SPORTSCENTER_USER" ("USER_ID") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TOOL_MANAGEMENT
--------------------------------------------------------

  ALTER TABLE "KIKAKU_USER"."TOOL_MANAGEMENT" ADD FOREIGN KEY ("TOOL_ID")
	  REFERENCES "KIKAKU_USER"."LENDING_TOOL" ("TOOL_ID") ENABLE;
  ALTER TABLE "KIKAKU_USER"."TOOL_MANAGEMENT" ADD CONSTRAINT "SYS_C006014" FOREIGN KEY ("RESERVE_MANAGEMENT_ID")
	  REFERENCES "KIKAKU_USER"."RESERVE_MANAGEMENT" ("RESERVE_MANAGEMENT_ID") ON DELETE CASCADE ENABLE;  
--------------------------------------------------------
--  DDL for Sequence SEQ_BBS
--------------------------------------------------------

   CREATE SEQUENCE  "KIKAKU_USER"."SEQ_BBS"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 54 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence SEQ_FACILITY
--------------------------------------------------------

   CREATE SEQUENCE  "KIKAKU_USER"."SEQ_FACILITY"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence SEQ_RESERVE_MANAGEMENT
--------------------------------------------------------

   CREATE SEQUENCE  "KIKAKU_USER"."SEQ_RESERVE_MANAGEMENT"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 27 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence SEQ_SPORTSCENTER_USER
--------------------------------------------------------

   CREATE SEQUENCE  "KIKAKU_USER"."SEQ_SPORTSCENTER_USER"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 48 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence SEQ_TOOL
--------------------------------------------------------

   CREATE SEQUENCE  "KIKAKU_USER"."SEQ_TOOL"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence SEQ_TOOL_MANAGEMENT
--------------------------------------------------------

   CREATE SEQUENCE  "KIKAKU_USER"."SEQ_TOOL_MANAGEMENT"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 42 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;

REM INSERTING into KIKAKU_USER.BULLETIN_BOARD
SET DEFINE OFF;
Insert into KIKAKU_USER.BULLETIN_BOARD (BULLETIN_BOARD_ID,CREATE_TIME,BBS_CONTENT,BBS_AUTHOR,BBS_TITLE) values (28,to_timestamp('06-12月-22 09.22.25.576000000 上午','DD-MON-RR HH.MI.SSXFF AM'),'権限機能（追加機能として、ページにあるのsessionチェックではなく、SpringSecurityとかの本物）','楊','TODOリスト');
Insert into KIKAKU_USER.BULLETIN_BOARD (BULLETIN_BOARD_ID,CREATE_TIME,BBS_CONTENT,BBS_AUTHOR,BBS_TITLE) values (29,to_timestamp('06-12月-22 09.22.38.505000000 上午','DD-MON-RR HH.MI.SSXFF AM'),' Validate機能（入力チェック）と全体のBug排除','楊','TODOリスト');
Insert into KIKAKU_USER.BULLETIN_BOARD (BULLETIN_BOARD_ID,CREATE_TIME,BBS_CONTENT,BBS_AUTHOR,BBS_TITLE) values (4,to_timestamp('05-12月-22 12.48.47.152000000 上午','DD-MON-RR HH.MI.SSXFF AM'),'sessionの有効期限は1分から30分に変更しました','楊','アップデート');
Insert into KIKAKU_USER.BULLETIN_BOARD (BULLETIN_BOARD_ID,CREATE_TIME,BBS_CONTENT,BBS_AUTHOR,BBS_TITLE) values (2,to_timestamp('05-12月-22 12.43.05.279000000 上午','DD-MON-RR HH.MI.SSXFF AM'),'施設一覧リニューアルしました（ジムの写真、とほかの施設の説明を頼む）','楊','アップデート');
Insert into KIKAKU_USER.BULLETIN_BOARD (BULLETIN_BOARD_ID,CREATE_TIME,BBS_CONTENT,BBS_AUTHOR,BBS_TITLE) values (3,to_timestamp('05-12月-22 12.46.50.465000000 上午','DD-MON-RR HH.MI.SSXFF AM'),'新規予約登録に複数の道具を追加可能になり、そしてすべての施設予約ページを一つにまとめました。入口は「施設‐施設選択‐予約」','楊','アップデート');
Insert into KIKAKU_USER.BULLETIN_BOARD (BULLETIN_BOARD_ID,CREATE_TIME,BBS_CONTENT,BBS_AUTHOR,BBS_TITLE) values (24,to_timestamp('06-12月-22 06.13.48.143000000 下午','DD-MON-RR HH.MI.SSXFF AM'),'各スポーツ施設の簡単な紹介と詳細な紹介を優先したいと思います。 そして、使用可能な道具のそれぞれの名前、機能、および説明。 (この部分はコードとは関係なし、文章だけを提供するほしい)','楊','TODOリスト');
Insert into KIKAKU_USER.BULLETIN_BOARD (BULLETIN_BOARD_ID,CREATE_TIME,BBS_CONTENT,BBS_AUTHOR,BBS_TITLE) values (41,to_timestamp('10-12月-22 10.00.25.885000000 下午','DD-MON-RR HH.MI.SSXFF AM'),'予約の新規（入力、確認、完了）、変更（入力、確認、完了）、削除（確認、完了）、一覧（普通ユーザー、管理者）のページと機能を完成','楊','アップデート');
Insert into KIKAKU_USER.BULLETIN_BOARD (BULLETIN_BOARD_ID,CREATE_TIME,BBS_CONTENT,BBS_AUTHOR,BBS_TITLE) values (42,to_timestamp('10-12月-22 10.02.32.607000000 下午','DD-MON-RR HH.MI.SSXFF AM'),'予約の入力画面にある施設をデータベースと連携した、直接にデータベースに増加すればいい。','楊','アップデート');
Insert into KIKAKU_USER.BULLETIN_BOARD (BULLETIN_BOARD_ID,CREATE_TIME,BBS_CONTENT,BBS_AUTHOR,BBS_TITLE) values (43,to_timestamp('10-12月-22 10.04.23.268000000 下午','DD-MON-RR HH.MI.SSXFF AM'),'各一覧画面にページ分け機能（ページング？）、JPAを利用して実現できるかもしれない。','楊','TODOリスト（追加機能）');
Insert into KIKAKU_USER.BULLETIN_BOARD (BULLETIN_BOARD_ID,CREATE_TIME,BBS_CONTENT,BBS_AUTHOR,BBS_TITLE) values (53,to_timestamp('15-12月-22 01.48.23.483000000 下午','DD-MON-RR HH.MI.SSXFF AM'),'ホームページのレイアウトを考えてほしい','楊','TODOリスト');
Insert into KIKAKU_USER.BULLETIN_BOARD (BULLETIN_BOARD_ID,CREATE_TIME,BBS_CONTENT,BBS_AUTHOR,BBS_TITLE) values (45,to_timestamp('10-12月-22 10.13.22.817000000 下午','DD-MON-RR HH.MI.SSXFF AM'),'予約のテンプレートページを八から三つ（input.html, confirm.html, complete.html）にまとめた。','楊','アップデート');
Insert into KIKAKU_USER.BULLETIN_BOARD (BULLETIN_BOARD_ID,CREATE_TIME,BBS_CONTENT,BBS_AUTHOR,BBS_TITLE) values (50,to_timestamp('15-12月-22 01.46.24.608000000 下午','DD-MON-RR HH.MI.SSXFF AM'),'すべての入力ボックスに動画とアイコンを実現した','楊','アップデート');
Insert into KIKAKU_USER.BULLETIN_BOARD (BULLETIN_BOARD_ID,CREATE_TIME,BBS_CONTENT,BBS_AUTHOR,BBS_TITLE) values (51,to_timestamp('15-12月-22 01.46.50.333000000 下午','DD-MON-RR HH.MI.SSXFF AM'),'ユーザーと予約のすべての機能が終わった','楊','アップデート');
Insert into KIKAKU_USER.BULLETIN_BOARD (BULLETIN_BOARD_ID,CREATE_TIME,BBS_CONTENT,BBS_AUTHOR,BBS_TITLE) values (52,to_timestamp('15-12月-22 01.47.42.275000000 下午','DD-MON-RR HH.MI.SSXFF AM'),'ユーザーと予約のすべての機能のテストをして欲しい','楊','TODOリスト（テスト）');

REM INSERTING into KIKAKU_USER.LENDING_FACILITY
SET DEFINE OFF;
Insert into KIKAKU_USER.LENDING_FACILITY (FACILITY_ID,FACILITY_NAME,FACILITY_ENG,EXPLANATION_LONG,EXPLANATION_SHORT) values (1,'アーチェリー',null,null,null);
Insert into KIKAKU_USER.LENDING_FACILITY (FACILITY_ID,FACILITY_NAME,FACILITY_ENG,EXPLANATION_LONG,EXPLANATION_SHORT) values (2,'サッカー',null,null,null);
Insert into KIKAKU_USER.LENDING_FACILITY (FACILITY_ID,FACILITY_NAME,FACILITY_ENG,EXPLANATION_LONG,EXPLANATION_SHORT) values (3,'テニス',null,null,null);
Insert into KIKAKU_USER.LENDING_FACILITY (FACILITY_ID,FACILITY_NAME,FACILITY_ENG,EXPLANATION_LONG,EXPLANATION_SHORT) values (4,'バスケットボール',null,null,null);
Insert into KIKAKU_USER.LENDING_FACILITY (FACILITY_ID,FACILITY_NAME,FACILITY_ENG,EXPLANATION_LONG,EXPLANATION_SHORT) values (5,'スケート場',null,null,null);
Insert into KIKAKU_USER.LENDING_FACILITY (FACILITY_ID,FACILITY_NAME,FACILITY_ENG,EXPLANATION_LONG,EXPLANATION_SHORT) values (6,'ボウリング場',null,null,null);


REM INSERTING into KIKAKU_USER.LENDING_TOOL
SET DEFINE OFF;
Insert into KIKAKU_USER.LENDING_TOOL (TOOL_ID,TOOL_NAME,FACILITY_ID) values (2,'矢',1);
Insert into KIKAKU_USER.LENDING_TOOL (TOOL_ID,TOOL_NAME,FACILITY_ID) values (3,'サッカーボール',2);
Insert into KIKAKU_USER.LENDING_TOOL (TOOL_ID,TOOL_NAME,FACILITY_ID) values (4,'スコアボード',2);
Insert into KIKAKU_USER.LENDING_TOOL (TOOL_ID,TOOL_NAME,FACILITY_ID) values (13,'プロテクター',5);
Insert into KIKAKU_USER.LENDING_TOOL (TOOL_ID,TOOL_NAME,FACILITY_ID) values (14,'ビブス',2);
Insert into KIKAKU_USER.LENDING_TOOL (TOOL_ID,TOOL_NAME,FACILITY_ID) values (5,'テニスラケット',3);
Insert into KIKAKU_USER.LENDING_TOOL (TOOL_ID,TOOL_NAME,FACILITY_ID) values (6,'テニスボール',3);
Insert into KIKAKU_USER.LENDING_TOOL (TOOL_ID,TOOL_NAME,FACILITY_ID) values (7,'バスケットボール',4);
Insert into KIKAKU_USER.LENDING_TOOL (TOOL_ID,TOOL_NAME,FACILITY_ID) values (8,'スコアボード',4);
Insert into KIKAKU_USER.LENDING_TOOL (TOOL_ID,TOOL_NAME,FACILITY_ID) values (9,'スケート靴',5);
Insert into KIKAKU_USER.LENDING_TOOL (TOOL_ID,TOOL_NAME,FACILITY_ID) values (10,'ヘルメット',5);
Insert into KIKAKU_USER.LENDING_TOOL (TOOL_ID,TOOL_NAME,FACILITY_ID) values (1,'弓',1);
Insert into KIKAKU_USER.LENDING_TOOL (TOOL_ID,TOOL_NAME,FACILITY_ID) values (11,'シューズ',6);

REM INSERTING into KIKAKU_USER.RESERVE_MANAGEMENT
SET DEFINE OFF;
Insert into KIKAKU_USER.RESERVE_MANAGEMENT (RESERVE_MANAGEMENT_ID,USER_ID,FACILITY_ID,CREATE_TIME,RESERVE_DATE,HOUR_LIST) values (26,47,3,to_timestamp('02-2月 -23 03.28.02.045000000 上午','DD-MON-RR HH.MI.SSXFF AM'),to_date('08-2月 -23','DD-MON-RR'),'17,18');
Insert into KIKAKU_USER.RESERVE_MANAGEMENT (RESERVE_MANAGEMENT_ID,USER_ID,FACILITY_ID,CREATE_TIME,RESERVE_DATE,HOUR_LIST) values (27,47,3,to_timestamp('02-2月 -23 03.28.21.763000000 上午','DD-MON-RR HH.MI.SSXFF AM'),to_date('08-2月 -23','DD-MON-RR'),'10');

REM INSERTING into KIKAKU_USER.SPORTSCENTER_USER
SET DEFINE OFF;
Insert into KIKAKU_USER.SPORTSCENTER_USER (USER_ID,NAME,PASSWORD,EMAIL,PHONE_NUMBER,POST,DOMICILE,AUTHORITY) values (47,'サンプルユーザー','09876','sample@mail.com','0353211111',1638001,'東京都新宿区西新宿2丁目8-1',0);
Insert into KIKAKU_USER.SPORTSCENTER_USER (USER_ID,NAME,PASSWORD,EMAIL,PHONE_NUMBER,POST,DOMICILE,AUTHORITY) values (48,'テストユーザー','12345','test@mail.com','0120305775',1130034,'東京都文京区湯島2丁目12-2',0);
Insert into KIKAKU_USER.SPORTSCENTER_USER (USER_ID,NAME,PASSWORD,EMAIL,PHONE_NUMBER,POST,DOMICILE,AUTHORITY) values (27,'管理者アカウント','54321','admin@mail.com','0338146151',1130033,'東京都文京区本郷3丁目23-16',1);

REM INSERTING into KIKAKU_USER.TOOL_MANAGEMENT
SET DEFINE OFF;
Insert into KIKAKU_USER.TOOL_MANAGEMENT (TOOL_MANAGEMENT_ID,RESERVE_MANAGEMENT_ID,TOOL_ID,TOOL_NUMBER) values (40,26,6,40);
Insert into KIKAKU_USER.TOOL_MANAGEMENT (TOOL_MANAGEMENT_ID,RESERVE_MANAGEMENT_ID,TOOL_ID,TOOL_NUMBER) values (41,27,5,4);
Insert into KIKAKU_USER.TOOL_MANAGEMENT (TOOL_MANAGEMENT_ID,RESERVE_MANAGEMENT_ID,TOOL_ID,TOOL_NUMBER) values (39,26,5,2);
Insert into KIKAKU_USER.TOOL_MANAGEMENT (TOOL_MANAGEMENT_ID,RESERVE_MANAGEMENT_ID,TOOL_ID,TOOL_NUMBER) values (42,27,6,1);
